# -*- coding: utf-8 -*-
"""PYTHON_ASSIGNMENT_3.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aUgjMG7NtG9c_y4QbNM759Y2s4BnQgAr

1.WAP to print your name 10 times
"""

print("Ankita Saha\n"*10)

"""2.WAP to print natural number from 1 to n.Enter the range: 10
The series is: 1 2 3 4 5 6 7 8 9 10
"""

n=int(input("Enter the range"))
for i in range(1,n+1):
  print(i,end=" ")

"""3.WAP to print the following series.
Enter the range: 20
1 3 5 7 9 11 13 15 17 19
"""

n=int(input("Enter the range"))
for i in range(1,n+1,2):
  print(i,end=" ")

"""4.WAP to calculate and display the factorial of
an inputted number.

"""

print("Enter the number:")
n=int(input())
if n==0:
  print("Factorial:1")
elif n<0:
  print("Factorial is defined only for non negative number")
else:
  factorial(n)

def factorial(n):
  fact=1
  for i in range(1,n+1):
          fact=fact*i
  print("Factorial of",n,"is",fact)

"""5.WAP to generate the table of an inputted
number using for loop.
Enter the number:3
3*1=3
3*2=6

"""

print("Enter the number:")
n=int(input())
for i in range(1,11):
  print(n,"*",i,"=",n*i)

"""6.WAP to display factors of an inputted
number
"""

print("Enter a number to find its factor:")
n=int(input())
print("Factors:",end=" ")
for i in range(1,n+1):
    if n%i==0:
      print (i,end=" ")

"""7.WAP to calculate sum of first n numbers.
1+2+…+n
"""

sum=0
print("Enter a number:")
n=int(input())
for i in range(1,n+1):
  sum=sum+i
print("The sum of first",n,"number is:",sum)

"""8.WAP to check whether an inputted number
is prime or not.
"""

def check_prime(n):
  c=0
  for i in range(2,n):
    if n%i==0:
      c=c+1
  return c

print("Enter a number:")
n=int(input())
p=check_prime(n)
if p==0:
  print("Prime")
else:
  print("Non Prime")

"""9.WAP to display all the prime number upto n."""

ran=int(input("Enter the number"))
print("Prime numbers:",end=" ")
for i in range(2,ran+1):
  p=check_prime(i)
  if p==0:
    print(i,end=" ")

"""10.WAP to print the following patterns using
loop
"""

ran=int(input("Enter number:"))
for i in range(1,ran+1):
  for j in range(1,i+1):
    print("*",end='')
  print()

def tripat():
  ran=int(input("Enter number:"))
  for i in range(1,ran+1):
    print("*"*i)
  print()
if __name__ == "__main__":
  tripat()

ran=int(input("Enter number:"))
for i in range(0,ran):
      print(" "*i,"A"*(ran-i))
print()

"""11.WAP to print the following patterns using
loop.

"""

k=1
ran=int(input("Enter number:"))
for i in range(1,ran+1):
      print(" "*(ran-i),"O"*k)
      k+=2
print()

k=7
for i in range(0,ran):
      print(" "*i,"O"*k)
      k-=2
print()

k=1
for i in range(1,5):
  for j in range(1,i+1):
    print(k,end=" ")
    k=k+1
  print()

"""12.WAP to print first n Fibonacci numbers."""

a=0
b=1
c=0
n=int(input("Enter the number:"))
print("0",end=' ')
for i in range(1,n):
  print(c,end=" ")
  c=a+b
  a=b
  b=c